### ISSUE TITLE
error in full chain itk 

### ISSUE THREAD

**Issue by rubihason** [acts-project/acts#1763]
Hello,
I was trying to run a full chain itk script in python, and I got this error:

```
11:23:25    buildITkGeom   INFO      Adding material from /root/Thesis/acts/Examples/Scripts/Python/acts-itk/itk-hgtd/material-maps-ITk-HGTD.json
Traceback (most recent call last):
  File "full_chain_itk.py", line 31, in <module>
    detector, trackingGeometry, decorators = acts.examples.itk.buildITkGeometry(geo_dir)
  File "/root/Thesis/acts/acts.build/python/acts/examples/itk.py", line 33, in buildITkGeometry
    matDeco = acts.IMaterialDecorator.fromFile(
  File "/root/Thesis/acts/acts.build/python/acts/__init__.py", line 56, in _decoratorFromFile
    return ActsPythonBindings.JsonMaterialDecorator(
RuntimeError: Unable to open input JSON material file: acts-itk/itk-hgtd/material-maps-ITk-HGTD.json
root@Rubi:~/Thesis/acts/Examples/Scripts/Python#
```

**Comment by paulgessinger** [comment]
Can you confirm the file is there and contains valid JSON? Do you have git lfs installed?

**Comment by rubihason** [comment]
Yes, i have:
```
root@Rubi:~/Thesis/acts/Examples/Scripts/Python# git lfs --version
git-lfs/2.9.0 (GitHub; linux amd64; go 1.12.7; git 8ab05aa7)
```
I can't find any acts-itk directory, this is weird. what does it mean? Do i need to "git pull"?

**Comment by paulgessinger** [comment]
You will need to clone the acts-itk repository from `gitlab.cern.ch/atlas/acts-itk`

**Comment by rubihason** [comment]
I can't get into CERN website, i don't have a Cern user.
Are there different ways to download this file?
