### ISSUE TITLE
Improve error messages informativeness in python bindings

### ISSUE THREAD

**Issue by tboldagh** [acts-project/acts#1802]
While working with python bindings for example algorithms it is sometimes quite difficult to understand the errors. An example is given below but a minimum reproduce would be make any typo or other mistake.
Here is a few that I provoked intentionally. The mistake made, the error they produce and a suggested error message.
They are all in seeding but it should generalise:
In seeding:
```
Correct: inputSpacePoints=[spacePoints], 
Mistake: inputSpacePoints=spacePoints  // wrong type

Traceback (most recent call last):
  File "../Examples/Scripts/Python/full_chain_itk.py", line 81, in <module>
    addSeeding(
  File "/ATLAS/tbold/acts/feature-add-ht-seeding-example/acts/install/python/acts/examples/__init__.py", line 168, in NamedTypeArgsWrapper
    return func(*newargs, **kwargs)
  File "/ATLAS/tbold/acts/feature-add-ht-seeding-example/acts/install/python/acts/examples/reconstruction.py", line 271, in addSeeding
    inputProtoTracks, inputSeeds = addStandardSeeding(
  File "/ATLAS/tbold/acts/feature-add-ht-seeding-example/acts/install/python/acts/examples/reconstruction.py", line 568, in addStandardSeeding
    seedingAlg = acts.examples.SeedingAlgorithm(
  File "/ATLAS/tbold/acts/feature-add-ht-seeding-example/acts/install/python/acts/_adapter.py", line 27, in wrapped
    setattr(cfg, k, v)
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: acts.ActsPythonBindings._examples.SeedingAlgorithm.Config, arg0: List[str]) -> None

Invoked with: <acts.ActsPythonBindings._examples.SeedingAlgorithm.Config object at 0x7f804ae24c30>, 'spacepoints'
```
Hoped for: The value provided for an argument for acts.examples.SeedingAlgorithm: inputSpacePoints should be list while it is a str

```
Correct: inputSpacePoints=[spacePoints],
Mistake: inputSPs=[spacePoints], // wrong arg name

Traceback (most recent call last):
  File "../Examples/Scripts/Python/full_chain_itk.py", line 81, in <module>
    addSeeding(
  File "/ATLAS/tbold/acts/feature-add-ht-seeding-example/acts/install/python/acts/examples/__init__.py", line 168, in NamedTypeArgsWrapper
    return func(*newargs, **kwargs)
  File "/ATLAS/tbold/acts/feature-add-ht-seeding-example/acts/install/python/acts/examples/reconstruction.py", line 271, in addSeeding
    inputProtoTracks, inputSeeds = addStandardSeeding(
  File "/ATLAS/tbold/acts/feature-add-ht-seeding-example/acts/install/python/acts/examples/reconstruction.py", line 568, in addStandardSeeding
    seedingAlg = acts.examples.SeedingAlgorithm(
  File "/ATLAS/tbold/acts/feature-add-ht-seeding-example/acts/install/python/acts/_adapter.py", line 30, in wrapped
    fn(self, cfg, *args, **_kwargs)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. acts.ActsPythonBindings._examples.SeedingAlgorithm(config: ActsExamples::SeedingAlgorithm::Config, level: acts.ActsPythonBindings.logging.Level)

Invoked with: <acts.ActsPythonBindings._examples.SeedingAlgorithm.Config object at 0x7f79b1934af0>; kwargs: level=<Level.VERBOSE: 0>, inputSPs=['spacepoints']
```
Hoped for: The keyword argument inputSPs can not be accepted, those are available: .... here the list follows ....

And probably a few more could be capture and "explained" to users.

Tagging @paulgessinger @benjaminhuth

**Comment by tboldagh** [comment]
I have just run into this kind of issue and got very reasonable error:
```
Patched config constructor failed for <class 'acts.ActsPythonBindings._examples.TrackSelector'>
This is most likely because one of the following kwargs could not be assigned to
the Config object, and the constructor did not accept it as an additional
argument:
-> level, removeNeutral
<class 'acts.ActsPythonBindings._examples.TrackSelector.Config'> has the following properties:
-> absEta, absEtaMax, absEtaMin, eta, etaMax, etaMin, inputTracks, loc0, loc0Max, loc0Min, loc1, loc1Max, loc1Min, outputTracks, phi, phiMax, phiMin, pt, ptMax, ptMin, time, timeMax, timeMin
```
and:
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. acts.ActsPythonBindings._examples.TrackSelector(config: ActsExamples::TrackSelector::Config, level: acts.ActsPythonBindings.logging.Level)

Invoked with: <acts.ActsPythonBindings._examples.TrackSelector.Config object at 0x7fbd959bac70>; kwargs: level=<Level.INFO: 2>, removeNeutral=True
```

Was there a fix? Should this be closed?

**Comment by andiwand** [comment]
I think paul improved this at some point? @paulgessinger

**Comment by paulgessinger** [comment]
Yeah I did, but didn't close this ticket. I'll do that now.
