### ISSUE TITLE
vertex fitting and duplicate tracks

### ISSUE THREAD

**Issue by rubihason** [acts-project/acts#1992]
Hello, while i running vertex fitting, i got error on each event.

'''
Number of fitted tracks and associated truth particles do not match. (48 != 14) Not able to match fitted tracks at reconstructed vertex to truth vertex. Switch to hit based truth matching. 
'''
I believe it came due to a large number of duplicate tracks. 

'''
12:52:16    SeedingPerfo   INFO      Efficiency (nMatchedParticles / nAllParticles) = 0.681481
12:52:16    SeedingPerfo   INFO      Fake rate (nUnMatchedSeeds / nAllSeeds) = 0.0011274
12:52:16    SeedingPerfo   INFO      Duplication rate (nDuplicatedMatchedParticles / nMatchedParticles) = 0.956522
12:52:16    SeedingPerfo   INFO      Average number of duplicated seeds ((nMatchedSeeds - nMatchedParticles) / nMatchedParticles) = 3.81522
'''
I simulated the event of PP to Z to Mu+ Mu-.
What can I do to fix this problem?

**Comment by andiwand** [comment]
did you try to use one of the ambiguity solvers? you can check out an example in the odd full chain here https://github.com/acts-project/acts/blob/main/Examples/Scripts/Python/full_chain_odd.py#L184-L206

**Comment by rubihason** [comment]
I tried but this is what I got when I ran full_chain_odd

'''
root@Rubi:~/Thesis/acts/Examples/Scripts/Python# python3 full_chain_odd.py
Error in <TFile::ReadBuffer>: error reading all requested bytes from file /root/Thesis/acts/thirdparty/OpenDataDetector/data/odd-material-maps.root, got 133 of 300thon#
Error in <TFile::Init>: /root/Thesis/acts/thirdparty/OpenDataDetector/data/odd-material-maps.root failed to read the file type data.
Traceback (most recent call last):cripts/Pyt
  File "full_chain_odd.py", line 60, in <module>
    oddMaterialDeco = acts.IMaterialDecorator.fromFile(oddMaterialMap)
  File "/root/Thesis/acts/acts.build/python/acts/__init__.py", line 60, in _decoratorFromFile
    return ActsPythonBindings._examples.RootMaterialDecorator(
  File "/root/Thesis/acts/acts.build/python/acts/_adapter.py", line 31, in wrapped
    fn(self, cfg, *args, **_kwargs)
RuntimeError: Could not open '/root/Thesis/acts/thirdparty/OpenDataDetector/data/odd-material-maps.root: iostream error
'''
