### ISSUE TITLE
ci: job `build_performance` fails after numpy 2.0.0 release

### ISSUE THREAD

**Issue by AJPfleger** [acts-project/acts#3309]
There seems to be a incompatibility between pandas and numpy.

Described in more detail in a similar issue here:
- https://github.com/numpy/numpy/issues/26710

I will try to fix this.

## Error
```
Run cmakeperf collect build/compile_commands.json -o perf.csv
  cmakeperf collect build/compile_commands.json -o perf.csv
  shell: sh -e {0}
  env:
    CTEST_OUTPUT_ON_FAILURE: 1
    CCACHE_DIR: /home/runner/work/acts/acts/ccache
    CCACHE_MAXSIZE: 500M
    CCACHE_KEY_SUFFIX: r1
    ACTS_LOG_FAILURE_THRESHOLD: WARNING
Traceback (most recent call last):
  File "/usr/local/bin/cmakeperf", line 5, in <module>
    from cmakeperf.cli import main
  File "/usr/local/lib/python3.10/dist-packages/cmakeperf/cli.py", line 17, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.10/dist-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/usr/local/lib/python3.10/dist-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.10/dist-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/usr/local/lib/python3.10/dist-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Error: Process completed with exit code 1.
```

**Comment by paulgessinger** [comment]
Seems like there was a problem with the dependency pinning
